# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import tarno_pb2 as tarno__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in tarno_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TarnoStub:
    """Main TARNO service: bidirectional stream for chat/commands plus unary helpers.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Stream = channel.stream_stream(
                '/tarno.Tarno/Stream',
                request_serializer=tarno__pb2.ClientMessage.SerializeToString,
                response_deserializer=tarno__pb2.ServerMessage.FromString,
                _registered_method=True)
        self.GetSystemInfo = channel.unary_unary(
                '/tarno.Tarno/GetSystemInfo',
                request_serializer=tarno__pb2.Empty.SerializeToString,
                response_deserializer=tarno__pb2.SystemInfo.FromString,
                _registered_method=True)
        self.SetApiKey = channel.unary_unary(
                '/tarno.Tarno/SetApiKey',
                request_serializer=tarno__pb2.ApiKeyRequest.SerializeToString,
                response_deserializer=tarno__pb2.ApiKeyResponse.FromString,
                _registered_method=True)
        self.GetApiKeyStatus = channel.unary_unary(
                '/tarno.Tarno/GetApiKeyStatus',
                request_serializer=tarno__pb2.Empty.SerializeToString,
                response_deserializer=tarno__pb2.ApiKeyStatusResponse.FromString,
                _registered_method=True)
        self.GetMemorySummary = channel.unary_unary(
                '/tarno.Tarno/GetMemorySummary',
                request_serializer=tarno__pb2.MemoryQuery.SerializeToString,
                response_deserializer=tarno__pb2.MemorySummary.FromString,
                _registered_method=True)
        self.ImportMemory = channel.unary_unary(
                '/tarno.Tarno/ImportMemory',
                request_serializer=tarno__pb2.ImportMemoryRequest.SerializeToString,
                response_deserializer=tarno__pb2.ImportMemoryResponse.FromString,
                _registered_method=True)
        self.Dictate = channel.unary_unary(
                '/tarno.Tarno/Dictate',
                request_serializer=tarno__pb2.DictateRequest.SerializeToString,
                response_deserializer=tarno__pb2.DictateResponse.FromString,
                _registered_method=True)
        self.GetModelCatalog = channel.unary_unary(
                '/tarno.Tarno/GetModelCatalog',
                request_serializer=tarno__pb2.Empty.SerializeToString,
                response_deserializer=tarno__pb2.ModelCatalog.FromString,
                _registered_method=True)
        self.GetMicrophoneDevices = channel.unary_unary(
                '/tarno.Tarno/GetMicrophoneDevices',
                request_serializer=tarno__pb2.Empty.SerializeToString,
                response_deserializer=tarno__pb2.MicrophoneDeviceList.FromString,
                _registered_method=True)
        self.GetSpeakerDevices = channel.unary_unary(
                '/tarno.Tarno/GetSpeakerDevices',
                request_serializer=tarno__pb2.Empty.SerializeToString,
                response_deserializer=tarno__pb2.SpeakerDeviceList.FromString,
                _registered_method=True)


class TarnoServicer:
    """Main TARNO service: bidirectional stream for chat/commands plus unary helpers.
    """

    def Stream(self, request_iterator, context):
        """Bidirectional stream. Client sends commands/chat; server pushes events, messages and status.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSystemInfo(self, request, context):
        """Request current system information.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetApiKey(self, request, context):
        """Write an LLM provider API key into the SecretsVault.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetApiKeyStatus(self, request, context):
        """Query which providers already have a key configured (values are never returned).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMemorySummary(self, request, context):
        """Block 6, Phase 54: fetch facts/episodes from the memory layer (Block 4)
        for the MemoryPage sidebar. Empty search returns everything (capped).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImportMemory(self, request, context):
        """Re-applies a (possibly manually corrected) memory export - the WinUI
        file picker already has the JSON bytes in memory, so this takes the
        text directly rather than a server-side file path.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Dictate(self, request, context):
        """Phase B: blocking, one-shot voice dictation into the chat text box - NOT
        part of the normal wake-word/voice-conversation loop. Unary (like
        SetApiKey) because it's a single request/response, not a stream event.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelCatalog(self, request, context):
        """Phase 1-6: the curated per-provider model list (rate-limit note +
        capability keywords) for the WinUI model picker. Static per provider
        except Ollama, which is queried live from the local Ollama server on
        each call (whatever the user has pulled) - so this is a plain unary
        call, not something cached client-side across the whole session.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMicrophoneDevices(self, request, context):
        """Settings microphone picker: enumerate real PortAudio input devices
        (including built-in laptop mic arrays) for the dropdown. Doesn't need a
        running voice session - AudioStream.list_input_devices() is a static
        enumeration.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSpeakerDevices(self, request, context):
        """Settings speaker picker - same shape as GetMicrophoneDevices, via
        pygame's SDL2 playback-device enumeration.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TarnoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Stream': grpc.stream_stream_rpc_method_handler(
                    servicer.Stream,
                    request_deserializer=tarno__pb2.ClientMessage.FromString,
                    response_serializer=tarno__pb2.ServerMessage.SerializeToString,
            ),
            'GetSystemInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemInfo,
                    request_deserializer=tarno__pb2.Empty.FromString,
                    response_serializer=tarno__pb2.SystemInfo.SerializeToString,
            ),
            'SetApiKey': grpc.unary_unary_rpc_method_handler(
                    servicer.SetApiKey,
                    request_deserializer=tarno__pb2.ApiKeyRequest.FromString,
                    response_serializer=tarno__pb2.ApiKeyResponse.SerializeToString,
            ),
            'GetApiKeyStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetApiKeyStatus,
                    request_deserializer=tarno__pb2.Empty.FromString,
                    response_serializer=tarno__pb2.ApiKeyStatusResponse.SerializeToString,
            ),
            'GetMemorySummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMemorySummary,
                    request_deserializer=tarno__pb2.MemoryQuery.FromString,
                    response_serializer=tarno__pb2.MemorySummary.SerializeToString,
            ),
            'ImportMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.ImportMemory,
                    request_deserializer=tarno__pb2.ImportMemoryRequest.FromString,
                    response_serializer=tarno__pb2.ImportMemoryResponse.SerializeToString,
            ),
            'Dictate': grpc.unary_unary_rpc_method_handler(
                    servicer.Dictate,
                    request_deserializer=tarno__pb2.DictateRequest.FromString,
                    response_serializer=tarno__pb2.DictateResponse.SerializeToString,
            ),
            'GetModelCatalog': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelCatalog,
                    request_deserializer=tarno__pb2.Empty.FromString,
                    response_serializer=tarno__pb2.ModelCatalog.SerializeToString,
            ),
            'GetMicrophoneDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMicrophoneDevices,
                    request_deserializer=tarno__pb2.Empty.FromString,
                    response_serializer=tarno__pb2.MicrophoneDeviceList.SerializeToString,
            ),
            'GetSpeakerDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSpeakerDevices,
                    request_deserializer=tarno__pb2.Empty.FromString,
                    response_serializer=tarno__pb2.SpeakerDeviceList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tarno.Tarno', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tarno.Tarno', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Tarno:
    """Main TARNO service: bidirectional stream for chat/commands plus unary helpers.
    """

    @staticmethod
    def Stream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/tarno.Tarno/Stream',
            tarno__pb2.ClientMessage.SerializeToString,
            tarno__pb2.ServerMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSystemInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tarno.Tarno/GetSystemInfo',
            tarno__pb2.Empty.SerializeToString,
            tarno__pb2.SystemInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetApiKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tarno.Tarno/SetApiKey',
            tarno__pb2.ApiKeyRequest.SerializeToString,
            tarno__pb2.ApiKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetApiKeyStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tarno.Tarno/GetApiKeyStatus',
            tarno__pb2.Empty.SerializeToString,
            tarno__pb2.ApiKeyStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMemorySummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tarno.Tarno/GetMemorySummary',
            tarno__pb2.MemoryQuery.SerializeToString,
            tarno__pb2.MemorySummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ImportMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tarno.Tarno/ImportMemory',
            tarno__pb2.ImportMemoryRequest.SerializeToString,
            tarno__pb2.ImportMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Dictate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tarno.Tarno/Dictate',
            tarno__pb2.DictateRequest.SerializeToString,
            tarno__pb2.DictateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelCatalog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tarno.Tarno/GetModelCatalog',
            tarno__pb2.Empty.SerializeToString,
            tarno__pb2.ModelCatalog.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMicrophoneDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tarno.Tarno/GetMicrophoneDevices',
            tarno__pb2.Empty.SerializeToString,
            tarno__pb2.MicrophoneDeviceList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSpeakerDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tarno.Tarno/GetSpeakerDevices',
            tarno__pb2.Empty.SerializeToString,
            tarno__pb2.SpeakerDeviceList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
